export const ACHIEVEMENTS = [
  {
    key: 'first_cast',
    title: 'First Cast',
    description: 'Log your very first catch',
    emoji: '🎯',
    xpBonus: 50,
  },
  {
    key: 'shark_hunter',
    title: 'Shark Hunter',
    description: 'Successfully catch any shark species',
    emoji: '🦈',
    xpBonus: 200,
  },
  {
    key: 'week_warrior',
    title: 'Week Warrior',
    description: 'Post catches 7 days in a row',
    emoji: '📅',
    xpBonus: 300,
  },
  {
    key: 'fan_favourite',
    title: 'Fan Favourite',
    description: 'Receive 50 total upvotes across all catches',
    emoji: '❤️',
    xpBonus: 150,
  },
  {
    key: 'ocean_explorer',
    title: 'Ocean Explorer',
    description: 'Catch 5 different saltwater species',
    emoji: '🌊',
    xpBonus: 200,
  },
  {
    key: 'freshwater_master',
    title: 'Freshwater Master',
    description: 'Catch 10 different freshwater species',
    emoji: '🏞️',
    xpBonus: 250,
  },
  {
    key: 'big_fish',
    title: 'Big Fish',
    description: 'Log a catch over 50 lbs',
    emoji: '🏋️',
    xpBonus: 200,
  },
  {
    key: 'legend_status',
    title: 'Living Legend',
    description: 'Reach Legend rank (10,000 XP)',
    emoji: '👑',
    xpBonus: 500,
  },
  {
    key: 'community_star',
    title: 'Community Star',
    description: 'Leave 20 comments on other anglers catches',
    emoji: '⭐',
    xpBonus: 100,
  },
  {
    key: 'species_collector',
    title: 'Species Collector',
    description: 'Log 25 different species',
    emoji: '📖',
    xpBonus: 400,
  },
]
