// NOTE: World record weights are approximate based on IGFA all-tackle records.
// Verify against official IGFA records at igfa.org before production use.

export const SPECIES_DATA = [
  // Freshwater
  { name: 'Largemouth Bass', emoji: '🐟', type: 'Freshwater', worldRecordLbs: 22 },
  { name: 'Smallmouth Bass', emoji: '🐟', type: 'Freshwater', worldRecordLbs: 12 },
  { name: 'Spotted Bass', emoji: '🐟', type: 'Freshwater', worldRecordLbs: 11 },
  { name: 'Peacock Bass', emoji: '🐟', type: 'Freshwater', worldRecordLbs: 27 },
  { name: 'Bluegill', emoji: '🐠', type: 'Freshwater', worldRecordLbs: 4.75 },
  { name: 'Crappie', emoji: '🐠', type: 'Freshwater', worldRecordLbs: 6 },
  { name: 'Yellow Perch', emoji: '🐠', type: 'Freshwater', worldRecordLbs: 4.3 },
  { name: 'Walleye', emoji: '🐟', type: 'Freshwater', worldRecordLbs: 25 },
  { name: 'Northern Pike', emoji: '🐟', type: 'Freshwater', worldRecordLbs: 55 },
  { name: 'Muskellunge', emoji: '🦈', type: 'Freshwater', worldRecordLbs: 67 },
  { name: 'Common Carp', emoji: '🐡', type: 'Freshwater', worldRecordLbs: 75 },
  { name: 'Grass Carp', emoji: '🐡', type: 'Freshwater', worldRecordLbs: 73 },
  { name: 'Channel Catfish', emoji: '🐡', type: 'Freshwater', worldRecordLbs: 58 },
  { name: 'Blue Catfish', emoji: '🐡', type: 'Freshwater', worldRecordLbs: 143 },
  { name: 'Flathead Catfish', emoji: '🐡', type: 'Freshwater', worldRecordLbs: 123 },
  { name: 'Rainbow Trout', emoji: '🎣', type: 'Freshwater', worldRecordLbs: 48 },
  { name: 'Brown Trout', emoji: '🎣', type: 'Freshwater', worldRecordLbs: 44 },
  { name: 'Brook Trout', emoji: '🎣', type: 'Freshwater', worldRecordLbs: 15 },
  { name: 'Lake Trout', emoji: '🎣', type: 'Freshwater', worldRecordLbs: 72 },
  { name: 'Chinook Salmon', emoji: '🐠', type: 'Both', worldRecordLbs: 97 },
  { name: 'Coho Salmon', emoji: '🐠', type: 'Both', worldRecordLbs: 33 },
  { name: 'Sockeye Salmon', emoji: '🐠', type: 'Both', worldRecordLbs: 15 },
  { name: 'Pink Salmon', emoji: '🐠', type: 'Both', worldRecordLbs: 14 },
  { name: 'Atlantic Salmon', emoji: '🐠', type: 'Both', worldRecordLbs: 79 },
  { name: 'Sturgeon', emoji: '🐉', type: 'Freshwater', worldRecordLbs: 468 },
  { name: 'Paddlefish', emoji: '🐉', type: 'Freshwater', worldRecordLbs: 144 },
  { name: 'Bowfin', emoji: '🐟', type: 'Freshwater', worldRecordLbs: 21 },
  { name: 'Gar', emoji: '🐊', type: 'Freshwater', worldRecordLbs: 279 },

  // Saltwater
  { name: 'Red Drum', emoji: '🐡', type: 'Saltwater', worldRecordLbs: 94 },
  { name: 'Black Drum', emoji: '🐡', type: 'Saltwater', worldRecordLbs: 113 },
  { name: 'Spotted Seatrout', emoji: '🎣', type: 'Saltwater', worldRecordLbs: 17 },
  { name: 'Snook', emoji: '🐟', type: 'Saltwater', worldRecordLbs: 53 },
  { name: 'Tarpon', emoji: '🦈', type: 'Saltwater', worldRecordLbs: 286 },
  { name: 'Bonefish', emoji: '🐟', type: 'Saltwater', worldRecordLbs: 19 },
  { name: 'Permit', emoji: '🐟', type: 'Saltwater', worldRecordLbs: 60 },
  { name: 'Striped Bass', emoji: '🐟', type: 'Both', worldRecordLbs: 81 },
  { name: 'Bluefish', emoji: '🐟', type: 'Saltwater', worldRecordLbs: 31 },
  { name: 'Mahi-mahi', emoji: '🌊', type: 'Saltwater', worldRecordLbs: 87 },
  { name: 'King Mackerel', emoji: '🦈', type: 'Saltwater', worldRecordLbs: 93 },
  { name: 'Spanish Mackerel', emoji: '🐟', type: 'Saltwater', worldRecordLbs: 13 },
  { name: 'Cobia', emoji: '🐟', type: 'Saltwater', worldRecordLbs: 135 },
  { name: 'Amberjack', emoji: '🐟', type: 'Saltwater', worldRecordLbs: 156 },
  { name: 'Jack Crevalle', emoji: '🐟', type: 'Saltwater', worldRecordLbs: 58 },
  { name: 'Black Sea Bass', emoji: '🐠', type: 'Saltwater', worldRecordLbs: 10 },
  { name: 'Flounder', emoji: '🐡', type: 'Saltwater', worldRecordLbs: 22 },
  { name: 'Halibut', emoji: '🐡', type: 'Saltwater', worldRecordLbs: 459 },
  { name: 'Cod', emoji: '🐟', type: 'Saltwater', worldRecordLbs: 98 },
  { name: 'Haddock', emoji: '🐟', type: 'Saltwater', worldRecordLbs: 14 },
  { name: 'Pollock', emoji: '🐟', type: 'Saltwater', worldRecordLbs: 50 },
  { name: 'Hake', emoji: '🐟', type: 'Saltwater', worldRecordLbs: 7 },
  { name: 'Whiting', emoji: '🐟', type: 'Saltwater', worldRecordLbs: 6 },
  { name: 'Herring', emoji: '🐠', type: 'Saltwater', worldRecordLbs: 1.5 },
  { name: 'Sardine', emoji: '🐠', type: 'Saltwater', worldRecordLbs: 1 },
  { name: 'Anchovy', emoji: '🐠', type: 'Saltwater', worldRecordLbs: 0.5 },
  { name: 'Mullet', emoji: '🐟', type: 'Saltwater', worldRecordLbs: 6 },

  // Tuna & Billfish
  { name: 'Bluefin Tuna', emoji: '🌊', type: 'Saltwater', worldRecordLbs: 1496 },
  { name: 'Yellowfin Tuna', emoji: '🌊', type: 'Saltwater', worldRecordLbs: 427 },
  { name: 'Bigeye Tuna', emoji: '🌊', type: 'Saltwater', worldRecordLbs: 392 },
  { name: 'Albacore', emoji: '🌊', type: 'Saltwater', worldRecordLbs: 88 },
  { name: 'Skipjack Tuna', emoji: '🌊', type: 'Saltwater', worldRecordLbs: 45 },
  { name: 'Blackfin Tuna', emoji: '🌊', type: 'Saltwater', worldRecordLbs: 49 },
  { name: 'Swordfish', emoji: '🌊', type: 'Saltwater', worldRecordLbs: 1182 },
  { name: 'Blue Marlin', emoji: '🌊', type: 'Saltwater', worldRecordLbs: 1805 },
  { name: 'White Marlin', emoji: '🌊', type: 'Saltwater', worldRecordLbs: 181 },
  { name: 'Sailfish', emoji: '🌊', type: 'Saltwater', worldRecordLbs: 142 },
  { name: 'Spearfish', emoji: '🌊', type: 'Saltwater', worldRecordLbs: 90 },

  // Snapper & Grouper
  { name: 'Red Snapper', emoji: '🐡', type: 'Saltwater', worldRecordLbs: 50 },
  { name: 'Mangrove Snapper', emoji: '🐡', type: 'Saltwater', worldRecordLbs: 18 },
  { name: 'Mutton Snapper', emoji: '🐡', type: 'Saltwater', worldRecordLbs: 30 },
  { name: 'Lane Snapper', emoji: '🐡', type: 'Saltwater', worldRecordLbs: 8 },
  { name: 'Yellowtail Snapper', emoji: '🐡', type: 'Saltwater', worldRecordLbs: 11 },
  { name: 'Gag Grouper', emoji: '🐡', type: 'Saltwater', worldRecordLbs: 80 },
  { name: 'Red Grouper', emoji: '🐡', type: 'Saltwater', worldRecordLbs: 42 },
  { name: 'Black Grouper', emoji: '🐡', type: 'Saltwater', worldRecordLbs: 113 },
  { name: 'Warsaw Grouper', emoji: '🐡', type: 'Saltwater', worldRecordLbs: 436 },
  { name: 'Goliath Grouper', emoji: '🐡', type: 'Saltwater', worldRecordLbs: 680 },

  // Sharks
  { name: 'Great White Shark', emoji: '🦈', type: 'Saltwater', worldRecordLbs: 2664 },
  { name: 'Tiger Shark', emoji: '🦈', type: 'Saltwater', worldRecordLbs: 1780 },
  { name: 'Bull Shark', emoji: '🦈', type: 'Saltwater', worldRecordLbs: 771 },
  { name: 'Hammerhead Shark', emoji: '🦈', type: 'Saltwater', worldRecordLbs: 1280 },
  { name: 'Blacktip Shark', emoji: '🦈', type: 'Saltwater', worldRecordLbs: 270 },
  { name: 'Spinner Shark', emoji: '🦈', type: 'Saltwater', worldRecordLbs: 190 },
  { name: 'Lemon Shark', emoji: '🦈', type: 'Saltwater', worldRecordLbs: 405 },
  { name: 'Sandbar Shark', emoji: '🦈', type: 'Saltwater', worldRecordLbs: 260 },
  { name: 'Nurse Shark', emoji: '🦈', type: 'Saltwater', worldRecordLbs: 330 },
  { name: 'Shortfin Mako Shark', emoji: '🦈', type: 'Saltwater', worldRecordLbs: 1221 },
  { name: 'Blue Shark', emoji: '🦈', type: 'Saltwater', worldRecordLbs: 528 },
  { name: 'Thresher Shark', emoji: '🦈', type: 'Saltwater', worldRecordLbs: 802 },
  { name: 'Porbeagle', emoji: '🦈', type: 'Saltwater', worldRecordLbs: 507 },
  { name: 'Dogfish', emoji: '🦈', type: 'Saltwater', worldRecordLbs: 21 },
]