export const TIPS = [
  'Fish early in the morning or just before sunset when water temperatures are cooler and fish are more active.',
  'Match your bait size to the forage in the water; oversized bait often spooks pressured fish.',
  'A slight chop on the surface can make fish feel safer and feed more aggressively.',
  'When the barometer drops, many species turn on and feed before the weather front arrives.',
  'Use a lighter leader when fish are line-shy and a heavier one when cover is thick.',
  'Pay attention to the moon phase because many species feed more heavily around the new and full moon.',
  'Fish the edges of weed lines, drop-offs, and current seams where bait naturally funnels.',
  'Keep your hooks sharp; a dull hook costs you more strikes than most anglers realize.',
  'On sunny days, target shaded banks, docks, and deeper structure where fish seek comfort.',
  'A slow retrieve often outperforms a fast one when fish are feeding cautiously.',
  'Try a different color bait if fish are striking but not committing; contrast matters.',
  'Tie your knots carefully and wet them before tightening to preserve line strength.',
  'During high pressure, fish may hold deeper, so adjust your presentation rather than forcing a shallow bite.',
  'Watch for surface activity and birds diving; they often point to bait schools and feeding fish.',
  'In cold water, downsizing your lure and slowing your cadence can be the difference between blanking and boating a fish.',
  'When targeting bass, pause your retrieve and let the bait sit for a beat to trigger followers.',
  'A quick spray of water on your hands before handling fish helps protect their slime coat.',
  'Leave a little slack in the line when setting the hook on a soft-mouthed fish to avoid pulling the bait away.',
  'Check your knots and terminal tackle often, especially after landing a hard-fighting fish.',
  'Fish the windward side of a lake or river where bait and oxygen are pushed into one place.',
  'During summer, dawn and dusk are often the best windows for active feeding.',
  'When the water is clear, natural colors and subtle presentations usually work best.',
  'A small change in retrieve speed can turn a non-bite into a hook-up in an instant.',
  'Keep your gear dry and clean; salt, mud, and grit wear down reels and lines quickly.',
  'If you are catch-and-release fishing, handle fish with wet hands and release them quickly.',
  'Reading current and structure is just as important as finding bait when you are searching for fish.',
  'The best anglers often fish less water but spend more time observing it.',
  'Watch the water for bait movement, swirls, and subtle disturbances before casting.',
  'When fish are suspended, use a lure that can be worked at the exact depth they are holding.',
  'A short, accurate cast often beats a long, sloppy one when you are targeting structure.',
  'Keep a small log of water temperature and conditions because patterns repeat over time.',
  'If a lure is getting fouled, change the hook or trailer rather than simply forcing the presentation.',
]
